[build]
target = "x86_64-unknown-linux-gnu"
rustflags = [
    "-C", "link-arg=-nostdlib",
    "-C", "link-arg=-static",
    "-C", "link-arg=-Wl,--build-id=none",
    "-C", "link-arg=-nostartfiles",
    "-C", "link-dead-code=no",
    "-C", "embed-bitcode=yes",
    "-C", "lto",
    "-C", "link-arg=-Wl,--gc-sections",
    "-C", "link-arg=-s",
]
